# version: '3'

# services:

#   db:
#     image: mysql:5.7
#     environment:
#       MYSQL_ROOT_PASSWORD: '123456'  
#       MYSQL_DATABASE: 'logistics'
#       MYSQL_USER: 'root'
#       MYSQL_PASSWORD: '123456'
      
#     ports:
#       - "3307:3306"
#     volumes:
#       - mysql_data:/var/lib/mysql
 
#   web:
#     build: .
#     command: python manage.py runserver 0.0.0.0:8000
#     volumes:
#       - .:/app
#     ports:
#       - "8000:8000"
#     depends_on:
#       - db
      
#     healthcheck:
#       test: ["CMD", "mysqladmin", "ping", "-h", "db", "-u", "root", "-p123456"]  

  
  

# volumes:
#   mysql_data:
#     driver: local

