version: '3'

services:
  web:
      build: .
      command: python manage.py runserver 0.0.0.0:8002
      ports:
          - 8002:8002





# version: '3'

# services:
#     web:
#         build: .
#         command: python manage.py runserver 0.0.0.0:8000
#         volumes:
#             - .:/app
#         ports:
#             - "8000:8000"

#     db:
#         image: mysql
#         environment:
#         MYSQL_DATABASE: 'dockerDB'
#         MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
#         volumes:
#         - ./datas/mysql/dbb:/var/lib/mysql
#         container_name: mysql_db


# # version: '3'

# services:

#   db:
#     image: mysql:5.7
#     environment:
#       MYSQL_ROOT_PASSWORD: '123456'  
#       MYSQL_DATABASE: 'logistics'
#       MYSQL_USER: 'root'
#       MYSQL_PASSWORD: '123456'
      
#     ports:
#       - "3307:3306"
#     volumes:
#       - mysql_data:/var/lib/mysql
 
#   web:
#     build: .
#     command: python manage.py runserver 0.0.0.0:8000
#     volumes:
#       - .:/app
#     ports:
#       - "8000:8000"
#     depends_on:
#       - db
      
#     healthcheck:
#       test: ["CMD", "mysqladmin", "ping", "-h", "db", "-u", "root", "-p123456"]  

  
  

# volumes:
#   mysql_data:
#     driver: local

