# Generated by Django 3.2.4 on 2023-07-19 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(blank=True, max_length=250, null=True)),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='create_timestamp')),
                ('last_update_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='last_update_timestamp')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=250, null=True)),
                ('last_name', models.CharField(blank=True, max_length=250, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=150, null=True)),
                ('company_name', models.CharField(blank=True, max_length=250, null=True)),
                ('email', models.EmailField(blank=True, max_length=250, null=True)),
                ('alternate_number', models.CharField(blank=True, max_length=250, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=250, null=True)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('adhar_card', models.CharField(blank=True, max_length=250, null=True)),
                ('reset_otp', models.CharField(blank=True, max_length=100, null=True)),
                ('profile_image_path', models.TextField(blank=True, null=True)),
                ('base64', models.TextField(blank=True, null=True)),
                ('profile_image', models.FileField(blank=True, null=True, upload_to='')),
                ('adhar_card_front_side_img', models.TextField(blank=True, null=True)),
                ('adhar_card_front_side_img_path', models.FileField(blank=True, null=True, upload_to='')),
                ('adhar_card_back_side_img', models.TextField(blank=True, null=True)),
                ('adhar_card_back_side_img_path', models.FileField(blank=True, null=True, upload_to='')),
                ('pan_card', models.CharField(blank=True, max_length=250, null=True)),
                ('pan_image_path', models.TextField(blank=True, null=True)),
                ('pan_card_base64', models.TextField(blank=True, null=True)),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True, verbose_name='create_timestamp')),
                ('last_update_timestamp', models.DateTimeField(auto_now_add=True, null=True, verbose_name='last_update_timestamp')),
                ('whatsup_number', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logisticsapp.city')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.userroleref')),
            ],
        ),
        migrations.CreateModel(
            name='Defaultmessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_message', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.CharField(blank=True, max_length=250, null=True)),
                ('notification_history', models.CharField(blank=True, max_length=3000, null=True)),
                ('driver_driving_license', models.CharField(blank=True, max_length=250, null=True)),
                ('badge', models.CharField(blank=True, max_length=250, null=True)),
                ('driving_license_image_path', models.CharField(blank=True, max_length=250, null=True)),
                ('validity_start_date_time', models.CharField(blank=True, max_length=250, null=True)),
                ('validity_end_date_time', models.CharField(blank=True, max_length=250, null=True)),
                ('driver_status', models.CharField(blank=True, max_length=100, null=True)),
                ('date_online', models.DateTimeField(blank=True, null=True)),
                ('date_offline', models.DateTimeField(blank=True, null=True)),
                ('license_img_front', models.FileField(blank=True, null=True, upload_to='')),
                ('license_img_back', models.FileField(blank=True, null=True, upload_to='')),
                ('license_expire_date', models.DateField(blank=True, null=True)),
                ('insurence_img', models.FileField(blank=True, null=True, upload_to='')),
                ('insurence_expire_date', models.DateField(blank=True, null=True)),
                ('passbook_img', models.FileField(blank=True, null=True, upload_to='')),
                ('fitness_certificate_front_side_img_path', models.FileField(blank=True, null=True, upload_to='')),
                ('fitness_certificate_back_side_img_path', models.FileField(blank=True, null=True, upload_to='')),
                ('fitness_certificate_expire_date', models.DateField(blank=True, null=True)),
                ('live_lattitude', models.CharField(blank=True, max_length=100, null=True)),
                ('live_longitude', models.CharField(blank=True, max_length=100, null=True)),
                ('is_online', models.BooleanField(default=False)),
                ('time', models.IntegerField(blank=True, null=True)),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True, verbose_name='create_timestamp')),
                ('last_update_timestamp', models.DateTimeField(auto_now_add=True, null=True, verbose_name='last_update_timestamp')),
                ('is_active', models.BooleanField(default=True)),
                ('subcription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.subscriptionplan')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logisticsapp.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='DriverDocumentExpiryvalidity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.CharField(blank=True, max_length=100, null=True)),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DriverDocumentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schedulehour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField(blank=True, max_length=250, null=True)),
                ('vehicle_number', models.CharField(blank=True, max_length=250, null=True)),
                ('vehicle_status', models.CharField(blank=True, max_length=250, null=True)),
                ('permit_front_side_img_path', models.FileField(blank=True, null=True, upload_to='')),
                ('permit_expire_date', models.DateField(blank=True, null=True)),
                ('registration_certificate_front_side_img_path', models.FileField(blank=True, null=True, upload_to='')),
                ('registration_certificate_back_side_img_path', models.FileField(blank=True, null=True, upload_to='')),
                ('rc_expire_date', models.DateField(blank=True, null=True)),
                ('pollution_certificate_front_side_img_path', models.FileField(blank=True, null=True, upload_to='')),
                ('emission_test_expire_date', models.DateField(blank=True, null=True)),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True, verbose_name='create_timestamp')),
                ('last_update_timestamp', models.DateTimeField(auto_now_add=True, null=True, verbose_name='last_update_timestamp')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type_name', models.CharField(blank=True, max_length=250, null=True)),
                ('capacity', models.CharField(blank=True, max_length=250, null=True)),
                ('size', models.CharField(blank=True, max_length=250, null=True)),
                ('details', models.CharField(blank=True, max_length=250, null=True)),
                ('per_km_price', models.CharField(blank=True, max_length=100, null=True)),
                ('per_min_price', models.CharField(blank=True, max_length=100, null=True)),
                ('min_charge', models.CharField(blank=True, max_length=100, null=True)),
                ('free_min', models.CharField(blank=True, max_length=100, null=True)),
                ('max_time_min', models.CharField(blank=True, max_length=100, null=True)),
                ('badge', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_type_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('offer_price', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_type_sub_images', models.JSONField(blank=True, null=True)),
                ('vehicle_description', models.JSONField(blank=True, null=True)),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='create_timestamp')),
                ('last_update_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='last_update_timestamp')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle_Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_period', models.CharField(blank=True, max_length=100, null=True)),
                ('date_subscribed', models.DateTimeField(blank=True, max_length=100, null=True)),
                ('expiry_date', models.DateTimeField(blank=True, max_length=100, null=True)),
                ('amount', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('is_amount_paid', models.BooleanField(default=False)),
                ('paid_through', models.CharField(blank=True, max_length=100, null=True)),
                ('type_of_service', models.CharField(blank=True, max_length=100, null=True)),
                ('validity_days', models.IntegerField(blank=True, null=True)),
                ('is_expired', models.BooleanField(default=False)),
                ('vehicle_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logisticsapp.vehicle')),
            ],
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicletypes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicletypes', to='logisticsapp.vehicletypes'),
        ),
        migrations.CreateModel(
            name='Sendmessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('def_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logisticsapp.defaultmessage')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logisticsapp.driver')),
            ],
        ),
        migrations.CreateModel(
            name='Remarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=100, null=True)),
                ('document_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logisticsapp.driverdocumentstatus')),
                ('driver_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logisticsapp.driver')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_order_id', models.CharField(blank=True, max_length=200, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=200, null=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=200, null=True)),
                ('vehicle_subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logisticsapp.vehicle_subscription')),
            ],
        ),
        migrations.CreateModel(
            name='Messagecustomised',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customise_msg', models.CharField(blank=True, max_length=100, null=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logisticsapp.driver')),
            ],
        ),
        migrations.AddField(
            model_name='driver',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='types', to='logisticsapp.vehicle'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logisticsapp.vehicle'),
        ),
        migrations.CreateModel(
            name='Customised_message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(blank=True, max_length=100, null=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logisticsapp.driver')),
            ],
        ),
    ]
