# Generated by Django 3.2.4 on 2023-07-19 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logisticsapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sendmessage',
            name='def_message',
        ),
        migrations.RemoveField(
            model_name='sendmessage',
            name='driver',
        ),
        migrations.DeleteModel(
            name='Messagecustomised',
        ),
        migrations.DeleteModel(
            name='Sendmessage',
        ),
    ]
