# Generated by Django 3.2.12 on 2022-10-27 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logisticsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customised_message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('message_type', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
