# Generated by Django 3.2.12 on 2022-10-31 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logisticsapp', '0002_customised_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_status',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
