# Generated by Django 3.2.4 on 2023-07-19 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logisticsapp', '0002_auto_20230719_1148'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Defaultmessage',
        ),
        migrations.DeleteModel(
            name='Master',
        ),
    ]
