# Generated by Django 3.2.12 on 2022-11-01 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logisticsapp', '0003_vehicle_vehicle_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='accept_or_decline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_status', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
