# Generated by Django 3.2.12 on 2023-03-02 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logisticsapp', '0003_vehicle_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='vehicle_status',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='status',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_status',
        ),
    ]
