# Generated by Django 3.2.4 on 2023-07-21 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_bookingdistance'),
        ('logisticsapp', '0003_auto_20230719_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role', to='masters.userroleref'),
        ),
    ]
