# Generated by Django 3.2.12 on 2023-03-02 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logisticsapp', '0004_auto_20230302_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_status',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
