# Generated by Django 3.2.12 on 2022-11-03 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logisticsapp', '0005_driverquries'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DriverQuries',
        ),
    ]
