# Generated by Django 3.2.12 on 2023-03-03 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logisticsapp', '0005_vehicle_vehicle_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle_subscription',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
