# Generated by Django 3.2.4 on 2023-07-24 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logisticsapp', '0005_alter_customuser_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='owner_driving_licence',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
