# Generated by Django 3.2.12 on 2023-03-03 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logisticsapp', '0006_vehicle_subscription_is_expired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='paragraph',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
