# Generated by Django 3.2.12 on 2023-03-06 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logisticsapp', '0007_auto_20230303_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentdetails',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='paymentdetails',
            name='create_timestamp',
        ),
        migrations.RemoveField(
            model_name='paymentdetails',
            name='in_order',
        ),
        migrations.RemoveField(
            model_name='paymentdetails',
            name='last_update_timestamp',
        ),
        migrations.RemoveField(
            model_name='paymentdetails',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='paymentdetails',
            name='provider',
        ),
        migrations.AddField(
            model_name='paymentdetails',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='paymentdetails',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='paymentdetails',
            name='razorpay_signature',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='paymentdetails',
            name='vehicle_subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logisticsapp.vehicle_subscription'),
        ),
    ]
