# Generated by Django 3.2.7 on 2023-09-25 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logisticsapp', '0008_rename_insurence_expire_date_driver_insurance_expire_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='emission_test_expire_date',
            new_name='emission_certificate_expire_date',
        ),
    ]
