# Generated by Django 3.2.12 on 2022-11-07 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logisticsapp', '0008_alter_driverquries_driver_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='vehicle_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logisticsapp.vehicle'),
        ),
    ]
