# Generated by Django 3.2.12 on 2023-03-06 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logisticsapp', '0009_vehicle_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
