# Generated by Django 3.2.4 on 2023-03-28 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logisticsapp', '0009_alter_driver_vehicle_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Defaultmessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_message', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DriverDocumentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Filesize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(blank=True, max_length=100, null=True)),
                ('size', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Messagecustomised',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customise_msg', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Remarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=100, null=True)),
                ('document_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logisticsapp.driverdocumentstatus')),
            ],
        ),
        migrations.CreateModel(
            name='Sendmessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('def_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logisticsapp.defaultmessage')),
            ],
        ),
        migrations.CreateModel(
            name='Subscriptionplan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_period', models.CharField(blank=True, max_length=100, null=True)),
                ('validity_days', models.IntegerField(blank=True, null=True)),
                ('amount', models.CharField(blank=True, max_length=100, null=True)),
                ('type_of_service', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle_Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_period', models.CharField(blank=True, max_length=100, null=True)),
                ('date_subscribed', models.DateTimeField(blank=True, max_length=100, null=True)),
                ('expiry_date', models.DateTimeField(blank=True, max_length=100, null=True)),
                ('amount', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('is_amount_paid', models.BooleanField(default=False)),
                ('paid_through', models.CharField(blank=True, max_length=100, null=True)),
                ('type_of_service', models.CharField(blank=True, max_length=100, null=True)),
                ('validity_days', models.IntegerField(blank=True, null=True)),
                ('is_expired', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameModel(
            old_name='accept_or_decline',
            new_name='DriverDocumentExpiryvalidity',
        ),
        migrations.RenameField(
            model_name='driverdocumentexpiryvalidity',
            old_name='vehicle_status',
            new_name='number_of_days',
        ),
        migrations.RemoveField(
            model_name='customised_message',
            name='name',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='base64',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='emission_test_expire_date',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='fitness_certificate_front_side_img',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='license_status',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='permit_expire_date',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='rc_expire_date',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='rc_img',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='vehicle_status',
        ),
        migrations.RemoveField(
            model_name='paymentdetails',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='paymentdetails',
            name='create_timestamp',
        ),
        migrations.RemoveField(
            model_name='paymentdetails',
            name='in_order',
        ),
        migrations.RemoveField(
            model_name='paymentdetails',
            name='last_update_timestamp',
        ),
        migrations.RemoveField(
            model_name='paymentdetails',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='paymentdetails',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='queries',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='permit_front_side_img',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='pollution_certificate_front_side_img',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='registration_certificate_back_side_img',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='registration_certificate_front_side_img',
        ),
        migrations.AddField(
            model_name='aboutus',
            name='alternate_phone_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customised_message',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logisticsapp.driver'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='driver',
            name='create_timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='create_timestamp'),
        ),
        migrations.AddField(
            model_name='driver',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='last_update_timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='last_update_timestamp'),
        ),
        migrations.AddField(
            model_name='driver',
            name='time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentdetails',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='paymentdetails',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='paymentdetails',
            name='razorpay_signature',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='queries',
            name='isfor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logisticsapp.userroleref'),
        ),
        migrations.AddField(
            model_name='queries',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='colour',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='emission_test_expire_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='permit_expire_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='rc_expire_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicletypes',
            name='free_min',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehicletypes',
            name='offer_price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehicletypes',
            name='per_min_price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehicletypes',
            name='vehicle_description',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicletypes',
            name='vehicle_type_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='vehicletypes',
            name='vehicle_type_sub_images',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='heading',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='paragraph',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='fitness_certificate_expire_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='insurence_expire_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='license_expire_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='DriverQuries',
        ),
        migrations.AddField(
            model_name='vehicle_subscription',
            name='vehicle_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logisticsapp.vehicle'),
        ),
        migrations.AddField(
            model_name='sendmessage',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logisticsapp.driver'),
        ),
        migrations.AddField(
            model_name='remarks',
            name='driver_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logisticsapp.driver'),
        ),
        migrations.AddField(
            model_name='messagecustomised',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logisticsapp.driver'),
        ),
        migrations.AddField(
            model_name='paymentdetails',
            name='vehicle_subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logisticsapp.vehicle_subscription'),
        ),
    ]
