# Generated by Django 3.2.4 on 2023-04-05 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logisticsapp', '0012_language_schedulehour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
