# Generated by Django 3.2.4 on 2023-04-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logisticsapp', '0013_alter_driver_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='date',
            new_name='date_offline',
        ),
        migrations.AddField(
            model_name='driver',
            name='date_online',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
