# Generated by Django 3.2.4 on 2023-07-12 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logisticsapp', '0014_auto_20230405_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverdocumentstatus',
            name='status_name',
        ),
        migrations.AddField(
            model_name='driverdocumentstatus',
            name='description',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driverdocumentstatus',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driverdocumentstatus',
            name='label',
            field=models.DateField(blank=True, null=True),
        ),
    ]
