# Generated by Django 3.2.4 on 2023-07-12 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logisticsapp', '0015_auto_20230712_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverdocumentstatus',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='driverdocumentstatus',
            name='label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
