# Generated by Django 3.2.4 on 2023-07-13 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logisticsapp', '0017_alter_driverdocumentstatus_due_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driverdocumentexpiryvalidity',
            old_name='number_of_days',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='driverdocumentstatus',
            old_name='description',
            new_name='status_name',
        ),
        migrations.RemoveField(
            model_name='driverdocumentstatus',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='driverdocumentstatus',
            name='label',
        ),
        migrations.AddField(
            model_name='driverdocumentexpiryvalidity',
            name='due_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='driverdocumentexpiryvalidity',
            name='label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
