"""
Django settings for logistics_project project.

Generated by 'django-admin startproject' using Django 3.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""


from pathlib import Path
from datetime import timedelta
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ksl6&0_jeh0c$0_avne%l6z=e_e$&eg1_#5)%yqpj=9d@qpga&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*','logisticsdev.thestorywallcafe.com','www.logisticsdev.thestorywallcafe.com']
# ALLOWED_HOSTS=[]

# Application definition

DEFAULT_APPS = [
    # 'jazzmin',
    #'jet.dashboard',
    #'jet',
    'channels',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
]
THIRD_PARTY_APPS = [
    'rest_framework',
    'rest_framework.authtoken',
    'django_filters',
    'drf_yasg',
    'corsheaders',
    'celery',
    'django_celery_results',
    'django_celery_beat',
    'import_export',
    # 'background_task',
    # 'channels'
]
LOCAL_APPS  = [
    'logisticsapp',
    'userModule',
    'driverModule',
    'account',
    'documents',
    'masters',
    
]

INSTALLED_APPS  =   DEFAULT_APPS + THIRD_PARTY_APPS + LOCAL_APPS
APPEND_SLASH=False

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',    
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'logistics_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'logistics_project.wsgi.application'
ASGI_APPLICATION = 'logistics_project.asgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }



# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'OPTIONS': {
#             'read_default_file': '/logistics_dev/auth/mysql.cnf',
#         },
#     }
# }


# DATABASES = {
#         'default': 
#         {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'logistics_dev',
#         'USER': 'root',    
#         'PASSWORD': 'Ekfrazo@123#',    
#         'HOST': '143.110.184.45',    
#         'PORT': '3306',     
#         }
#     }

DATABASES = {
        'default': 
        {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'logistics',
        'USER': 'logistics_users',    
        'PASSWORD': 'Ekfrazo@123#',    
        'HOST': '143.110.184.45',    
        'PORT': '3306',     
        }
    }

# DATABASES = {
#         'default': 
#         {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'logistics',
#         'USER': 'root',    
#         'PASSWORD': 'Ekfrazo@123#',    
#         'HOST': '143.110.184.45',    
#         'PORT': '3306',     
#         }
#     }








JAZZMIN_UI_TWEAKS = {
    "theme": "simplex",
    # "dark_mode_theme": "darkly",
}



# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]



CELERY_RESULT_BACKEND = 'redis://127.0.0.1:6379'
CELERY_BROKER_URL = 'redis://127.0.0.1:6379'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TASK_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Kolkata'
CELERY_ACCEPT_CONTENT = ['application/json']

CELERY_BEAT_SCHEDULE = {
    'call-api-task': {
        'task': 'userModule.tasks.call_api_task',
        'schedule': 1.0  # Every 1 second
    },
}


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'logisticscom70@gmail.com'
EMAIL_HOST_PASSWORD = 'lemavpvxaixyijoq'
EMAIL_USE_TLS = True
APPLICATION_EMAIL = 'Admin<test@gmail.com>'
DEFAULT_FROM_EMAIL = 'Admin<test@gmail.com>'


SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=10),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=2),


    'AUTH_HEADER_TYPES': ('Bearer',),

}





# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_L10N = True

USE_TZ = True


JWT_SECRET_KEY = os.getenv('JWT_SECRET_KEY')



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/statics/'
MEDIA_URL = '/media/'


STATIC_ROOT="/logistics_dev/site/public/static"
MEDIA_ROOT="/logistics_dev/site/public/media"

CORS_ORIGIN_ALLOW_ALL   = True
CORS_ALLOW_CREDENTIALS  = True

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


CORS_ALLOW_HEADERS = [
'accept',
'accept-encoding',
'authorization',
'content-type',
'dnt',
'origin',
'user-agent',
'x-csrftoken',
'x-requested-with',
]

CORS_ALLOW_METHODS = [
'DELETE',
'GET',
'OPTIONS',
'PATCH',
'POST',
'PUT',
]

CORS_ALLOWED_ORIGINS = [
"https://logistics.thestorywallcafe.com",
"http://localhost:4200",
"http://127.0.0.1:8000",
]


RAZOR_KEY_ID = 'rzp_test_GxaJhvoS78ZpIz'
RAZOR_KEY_SECRET = 'SYBvWXndjCMdfCk7VBJ6pZei'


# CHANNEL_LAYERS = {
#     "default": {
#         "BACKEND": "channels.layers.InMemoryChannelLayer"
#     }
# }

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("127.0.0.1", 6379)],
        },
    },
}


