# Generated by Django 3.2.4 on 2023-07-20 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingDistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold_value', models.IntegerField()),
                ('incremented_value', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
