# Generated by Django 3.2.4 on 2023-07-21 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_bookingdistance'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdistance',
            name='last_km_value',
            field=models.IntegerField(blank=2, null=True),
        ),
    ]
