# Generated by Django 3.2.4 on 2023-07-21 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0004_alter_queries_isfor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
