# Generated by Django 3.2.4 on 2023-07-21 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0005_alter_subscriptionplan_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queries',
            name='isfor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='is_for', to='masters.userroleref'),
        ),
    ]
