# Generated by Django 3.2.4 on 2023-07-19 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logisticsapp', '0001_initial'),
        ('masters', '0001_initial'),
        ('django_celery_beat', '0015_edit_solarschedule_events_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.CharField(blank=True, max_length=250, null=True)),
                ('travel_details', models.CharField(blank=True, max_length=200, null=True)),
                ('is_bill_required', models.BooleanField(default=False)),
                ('is_bill_recived', models.BooleanField(default=False)),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True, verbose_name='create_timestamp')),
                ('last_update_timestamp', models.DateTimeField(auto_now_add=True, null=True, verbose_name='last_update_timestamp')),
                ('request_cancel', models.CharField(blank=True, max_length=100, null=True)),
                ('ordered_time', models.DateTimeField(blank=True, null=True)),
                ('pickedup_time', models.DateTimeField(blank=True, null=True)),
                ('order_accepted_time', models.DateTimeField(blank=True, null=True)),
                ('canceled_time', models.DateTimeField(blank=True, null=True)),
                ('order_droped_time', models.DateTimeField(blank=True, null=True)),
                ('declined_time', models.DateTimeField(blank=True, null=True)),
                ('trip_ended_time', models.DateTimeField(blank=True, null=True)),
                ('request_canceled_ride_time', models.DateTimeField(blank=True, null=True)),
                ('accept_canceled_ride_time', models.DateTimeField(blank=True, null=True)),
                ('decline_canceled_ride_time', models.DateTimeField(blank=True, null=True)),
                ('sub_user_phone_numbers', models.JSONField(blank=True, null=True)),
                ('actual_time_taken_to_complete', models.CharField(blank=True, max_length=200, null=True)),
                ('total_amount_without_actual_time_taken', models.FloatField(blank=True, null=True)),
                ('is_scheduled', models.BooleanField(default=False)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logisticsapp.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(blank=True, max_length=200, null=True)),
                ('location_detail', models.JSONField(blank=True, null=True)),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('total_estimated_cost', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logisticsapp.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleAssingedToDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date_and_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='last_update_timestamp')),
                ('new_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_driver', to='logisticsapp.customuser')),
                ('old_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='old_driver', to='logisticsapp.customuser')),
                ('vehicle_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logisticsapp.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('review', models.CharField(blank=True, max_length=200, null=True)),
                ('rating_given_by', models.TextField(blank=True, null=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_id', to='logisticsapp.customuser')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userModule.orderdetails')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to='logisticsapp.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='statusRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_accepted', models.BooleanField(default=False)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='logisticsapp.customuser')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userModule.orderdetails')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.status')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='logisticsapp.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date_and_time', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userModule.bookingdetail')),
                ('periodic_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.periodictask')),
            ],
        ),
        migrations.AddField(
            model_name='bookingdetail',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userModule.orderdetails'),
        ),
        migrations.AddField(
            model_name='bookingdetail',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.status'),
        ),
    ]
