# Generated by Django 3.2.4 on 2023-03-28 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logisticsapp', '0010_auto_20230328_1305'),
        ('django_celery_beat', '0015_edit_solarschedule_events_choices'),
        ('userModule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdetail',
            name='actual_time_taken_to_complete',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bookingdetail',
            name='is_scheduled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookingdetail',
            name='sub_user_phone_numbers',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookingdetail',
            name='total_amount_without_actual_time_taken',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_id', to='logisticsapp.customuser'),
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='rating_given_by',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userfeedback',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='userfeedback',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to='logisticsapp.customuser'),
        ),
        migrations.CreateModel(
            name='VehicleAssingedToDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date_and_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='last_update_timestamp')),
                ('new_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_driver', to='logisticsapp.customuser')),
                ('old_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='old_driver', to='logisticsapp.customuser')),
                ('vehicle_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logisticsapp.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date_and_time', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userModule.bookingdetail')),
                ('periodic_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.periodictask')),
            ],
        ),
    ]
