# Generated by Django 3.2.12 on 2023-03-09 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logisticsapp', '0011_auto_20230309_1715'),
        ('userModule', '0002_bookingdetail_total_amount_without_actual_time_taken'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleAssingedToDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date_and_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='last_update_timestamp')),
                ('new_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_driver', to='logisticsapp.customuser')),
                ('old_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='old_driver', to='logisticsapp.customuser')),
                ('vehicle_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logisticsapp.vehicle')),
            ],
        ),
    ]
