# Generated by Django 3.2.7 on 2023-09-27 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userModule', '0002_bookingdetail_vehicle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdetail',
            name='is_all_mobile_number_verified',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
