# Generated by Django 3.2.12 on 2023-03-13 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logisticsapp', '0011_auto_20230309_1715'),
        ('userModule', '0003_vehicleassingedtodriver'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdetail',
            name='is_scheduled',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ScheduledOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date_and_time', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logisticsapp.customuser')),
            ],
        ),
    ]
