# Generated by Django 3.2.12 on 2023-03-14 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userModule', '0004_auto_20230313_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledorder',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userModule.bookingdetail'),
        ),
    ]
