# Generated by Django 3.2.12 on 2023-03-28 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0015_edit_solarschedule_events_choices'),
        ('userModule', '0005_alter_scheduledorder_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledorder',
            name='periodic_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.periodictask'),
        ),
    ]
