# Generated by Django 3.2.4 on 2023-03-31 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userModule', '0006_scheduledorder_periodic_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdetail',
            name='accept_canceled_ride_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookingdetail',
            name='declin_canceled_ride_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookingdetail',
            name='declined_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookingdetail',
            name='inprogress_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookingdetail',
            name='request_canceled_ride_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookingdetail',
            name='trip_ended_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
