# Generated by Django 3.2.4 on 2023-03-31 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userModule', '0007_auto_20230331_1511'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingdetail',
            old_name='declin_canceled_ride_time',
            new_name='decline_canceled_ride_time',
        ),
    ]
