# Generated by Django 3.2.4 on 2023-04-04 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userModule', '0008_rename_declin_canceled_ride_time_bookingdetail_decline_canceled_ride_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingdetail',
            name='inprogress_time',
        ),
    ]
